### ISSUE TITLE
Browser->Name Not working

### ISSUE THREAD

**Issue by AustenZeh** [WhichBrowser/WhichBrowser#38]
Every time I write code like so: 

$user = new WhichBrowser($agents);
$user->analyseUserAgent($agents['ua']);
$browser = $user->browser->name;

where agents is an array of Agent Strings, I get an error that reads:

Notice: Undefined property: stdClass::$name in.....

and I was hoping someone could help me out, because it does the same thing for when I try to get the version of the browser or the OS. Really the only thing that works is when I analyse the device so please help, thank you!

**Comment by matinaspatsos** [comment]
Undefined property: stdClass::$name means that you have an undefined object. If I remember correctly, I think the reason why is because it is expecting a single agent string string instead of an array. I think you will have to loop through, and do $user = new WhichBrowser($agents); with each agent string.

To start to debug, walkthrough and var_dump everything. So do something like this: Try this:

$user = new WhichBrowser($agents);
var_dump($user);

// If it produces errors here, that probably means that $agents is not the data type that the WhichBrowser object is expecting.
$user = new WhichBrowser($agents);
var_dump($user);


$browser = $user->browser->name;
var_dump($browser);

Try that and see where you get the error.

________________________________

**Comment by NielsLeenheer** [comment]
Using WhichBrowser from PHP isn't officially supported yet, but if you do want to use it, you need pass an options array with the headers to the WhichBrowser object. Also keep in mind that name is not always defined. Only when WhichBrowser knows the name it will set this property.

```
$options = array('headers' => getallheaders());
$user = new WhichBrowser($options);

if (isset($user->browser->name)) {
   echo $user->browser->name;
} else {
   echo "Browser name is not known";
}
```

If you just have a user agent string you want to analyse you need to do it like this:

```
$options = array('headers' => array('User-Agent' => 'Mozilla/5.0........'));
$user = new WhichBrowser($options);

if (isset($user->browser->name)) {
   echo $user->browser->name;
} else {
   echo "Browser name is not known";
}
```
